M48
; DRILL file {KiCad (6.0.0)} date Fri Feb  3 10:22:31 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-03T10:22:31+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0512
%
G90
G05
T1
X8.335Y-4.6024
X8.5626Y-4.6024
T2
X9.5165Y-3.3854
T3
X9.2213Y-3.3854
T0
M30
